export type Project = {
  id: string;
  slug: string;
  title: string;
  tagline: string;
  description: string;
  problem?: string;
  solution?: string;
  role?: string;
  challenges?: string;
  techStack: string[];
  features?: string[];
  heroImage?: string;
  screenshots?: string[];
  liveUrl?: string;
  githubUrl?: string;
  videoUrl?: string;
  status?: string;
  featured?: boolean;
  displayOrder?: number;
};